# Generated by Django 5.0.6 on 2024-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
