# Generated by Django 5.0.6 on 2024-06-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_current_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fiction', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
