# Generated by Django 5.0.6 on 2024-06-04 12:46

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_images/no_image.jpg', storage=book.models.OverwriteStorage(), upload_to=book.models.image_directory_name),
        ),
    ]
